### PR TITLE
Deprecate specification

### PR DESCRIPTION
**Pull request by peterbrightwell**
As per Steering/BoD decision today

### CODE REVIEW

**Comment by peterbrightwell** [comment]
Perhaps `spec.yml` should include `show_in_index: false` so it doesn't appear on https://github.com/AMWA-TV/nmos and in the menus?

**Comment by pedro-alves-ferreira** [comment]
> Perhaps `spec.yml` should include `show_in_index: false` so it doesn't appear on https://github.com/AMWA-TV/nmos and in the menus?

What if it was there but clearly marked as deprecated? Would it be difficult to add another flag to render it differently? Otherwise, how would one find it?

**Comment by peterbrightwell** [comment]
Probably best to leave it in the index (could be in a separate section for deprecated specs?) but we could omit it from the IS menu.

Could have a tickbox to show Deprecated specifications (and one for WIP specs?) 

In any case that shouldn't affect approval of this PR

**Review by pedro-alves-ferreira — APPROVED** [review]
LGTM

**Pull request merged**
