### PR TITLE
Incorporate existing requirements on LLDP from the schemas into the docs

### LINKED ISSUE #32: Clarify constraints on a Network Device's LLDP configuration
LLDP (IEEE 802.1AB) seems to allow both Chassis ID and Port ID to use a number of sub-types.

In IS-06, the JSON schemas and documentation require that a Network Device's `chassis_id` MUST be the MAC address and the `port_id` MUST be the "Ethernet Interface information" or "the `ifAlias`".

However I think the spec would benefit from a clear statement that requires the LLDP emitted by the Network Device (switch) to correspond, identifying the relevant sub-types.

### PR DESCRIPTION
**Pull request by garethsb**
An attempt to resolve #32.

### CODE REVIEW

**Comment by garethsb** [comment]
Minor wording updates based on review.

We wonder whether it should be explicitly called out in the API spec (RAML) that the Network Controller can respond with a 400 Bad Request (and a helpful NMOS error body) if the `chassis_id`, `port_id` and `attached_network_device` information do not agree with the information held by the network controller/switch? (There is significant redundancy here, so the NC is able to double or triple check that the request makes sense!)

https://github.com/AMWA-TV/nmos-network-control/blob/v1.0.x/APIs/NetworkControlAPI.raml#L181-L183

**Review by andrewbonney — APPROVED** [review]
All looks good based upon what the API currently requires. I wonder if it might be worth re-considering whether it's really necessary to mandate the LLDP subtypes used by 'network devices' in the future. This does seem rather constraining and may mean that some switches simply couldn't participate in an IS-06 system due to their (perfectly valid) LLDP implementation.

**Comment by garethsb** [comment]
> All looks good based upon what the API currently requires. I wonder if it might be worth re-considering whether it's really necessary to mandate the LLDP subtypes used by 'network devices' in the future. This does seem rather constraining and may mean that some switches simply couldn't participate in an IS-06 system due to their (perfectly valid) LLDP implementation.

Thanks, Andrew. Yes, that was my intent, to elucidate in the doc what the current spec versions already require. It would be good to have input from several NC/switch vendors (and Endpoint manufacturers, and users, obviously) as to whether these constraints are reasonable.

**Comment by NEOAdvancedTechnology** [comment]
To be discussed offline

**Comment by garethsb** [comment]
Given the above, and discussion on the call yesterday, the following is an alternative proposal.

1. Relax the JSON schema requirements for Network Device `"chassis_id"`, and `"interface"` `"port_id"` (and thus Network Link `"port_id"`), to say only that respectively Chassis ID of MAC Address and Port ID of ifAlias are recommended, and that where LLDP is implemented on an interface, the LLDP Chassis ID and Port ID should match these values.

   The documentation would point out that if the above recommendation isn't followed, it's going to be much harder for the matching information to get from the switch interface to the Endpoint (IS-04 Node) to the BC (via IS-04 `"attached_network_device"`) and back to the Network Control API (in Endpoint `"attached_network_device"`).

2. The requirement for Endpoint `"chassis_id"` is already written in that style. Endpoint `"port_id"` currently says simply "MAC address of the endpoint." Add a sentence that says where LLDP is implemented by the Endpoint, the Port ID should match this value.

I think that would be a super-set of the current v1.0, align with IS-04, and correspond with current TR-1001-1 direction.

**Comment by garethsb** [comment]
Closing in favour of #62.

**Pull request closed without merging**
